import os


CONTROL_PORT = 8998
DATA_PORT = 8999

AUTH_TIMEOUT = 5
RESPONSE_TIMEOUT = 30

DISCOVER_TIMEOUT = 120
INIT_TIMEOUT_USRP = 300
INIT_TIMEOUT_DEFAULT = 120
DEVICE_OP_POLL_INTERVAL = 2.0
DEVICE_OP_COMMAND_TIMEOUT = 30
DISCOVERY_CACHE_TTL = 60

STREAMING_COMMAND_TIMEOUT = 45

SESSION_TEARDOWN_TIMEOUT = 10

DPIC_BALANCE_TIMEOUT = 900
DPIC_BALANCE_POLL_INTERVAL = 0.5

SHARED_SECRET = os.environ.get("BIOVIEW_SHARED_SECRET", "bioview-default-shared-secret")
