"""Depths for the bounded streaming queues, in chunks."""

RX_QUEUE_DEPTH = 8

SAVE_QUEUE_DEPTH = 64

SAVE_OUTPUT_QUEUE_DEPTH = 256

DISPLAY_QUEUE_DEPTH = 16

DATA_OUTPUT_QUEUE_DEPTH = 32

QUEUE_PUT_TIMEOUT_S = 0.1
